core:
  mode: "debug" # release, debug, test
  server_name: "social-network"
  port: 9090
mysql:
  host: "127.0.0.1"
  port: "4306"
  db: "service"
  user: "root"
  pass: ""
log:
  level: debug
  discard_output: false
mongo:
  address: "localhost:27017"
  username: "social"
  password: "social"
